name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.common.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set common outputs
        id: common
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: arm64

    needs:
      - prepare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Build
        id: build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          base_name="hello-http-${{ needs.prepare.outputs.short_sha }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          echo "base_name=$base_name" >> "$GITHUB_OUTPUT"
          bin_name="$base_name"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            bin_name="$bin_name.exe"
          fi
          go build -v -o "bin/$bin_name" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.base_name }}
          path: bin/

  prerelease:
    name: Prerelease
    permissions: write-all
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: bin/

      - name: Delete prerelease assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: prerelease-${{ github.ref_name }}
          deleteOnlyFromDrafts: false

      - name: Prerelease
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: 'Prerelease: ${{ github.ref_name }}'
          tag_name: prerelease-${{ github.ref_name }}
          body: "Build for commit ${{ needs.prepare.outputs.short_sha }}"
          files: bin/*
